typesense/typesense-api-spec

- openapi.yml
- Changes to accommodate new features added in v0.20 and v0.21
- Structure of query parameters changed to suit all API generators.
> New features and query parameter changes

- openapi.yml
> update: v0.22.0

- openapi.yml
Remove Field Type enum to make it simply a string constant
> Remove enum from Field Type

- openapi.yml
Add missing parameters:
-  `split_join_tokens` 
-  `prioritize_token_position`
- `max_candidates`
> Add split_join_tokens and prioritize_token_position to search parameters

- openapi.yml
* added the Infix search options to the spec so they can be used to generate fully featured clients (specifically go-lang)
> add infix search support options

- openapi.yml
Adds support for `enable_nested_fields` parameter to create collection.
> Added support for 'enable_nested_fields' parameter

- openapi.yml
> Added types for embedding generation

- openapi.yml
> Add required fields for remote embedding

- openapi.yml
Add found field into grouped_hits
> Add found property to grouped_hits

- openapi.yml
> Fix expires_at

- openapi.yml
Add reference for the stopwords.
> Add stopwords reference

- openapi.yml
* Added stopwords parameter to the possible search parameters
> Add stopwords parameter to search parameters

- openapi.yml
> Add support for presets

- openapi.yml
> Fix retrieve a single stopwords set response schema, add metrics & stats endpoint

- openapi.yml
fix for this issue:
https://github.com/typesense/typesense-java/issues/55
- [ x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).
> fix: add missing parameter "return_id"

- openapi.yml
> Update synonym schema

- openapi.yml
Fix https://github.com/typesense/typesense-go/issues/182
> add `found_docs` field in `SearchResult`

- openapi.yml
Added the new v27.0 search parameters & conversation API
Also include https://github.com/typesense/typesense-api-spec/pull/69
> Add conversation API & update search params

- openapi.yml
> Add `url` field in `model_config` resolve #59

- openapi.yml
> Add `dirty_values` parameter for single document update

- openapi.yml
> revert: make `action` and `dirty_values` children of import param

- openapi.yml
- added `refresh_token`, `indexing_prefix` and `query_prefix`
> feat: update collection `model_config` schema

- openapi.yml
fixed https://github.com/typesense/typesense-api-spec/issues/50
> fix: enclose http status code in quotation marks

- openapi.yml
resolve https://github.com/typesense/typesense-go/issues/186
> add definition for search result hit `text_match_info`

- openapi.yml
Add parameters for v29 updates for natural language queries
> Natural language

- openapi.yml
> update: API spec with curations
